/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgresqlproject;

import java.awt.BorderLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.ParserConfigurationException;

import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;
/**
 *
 * @author Marina Bykov
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    
    public MainPage() {
        
        try {
            currentDB = new SQLqueries();
            currentDB.createTablesAndSequences();
            initComponents();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
            "Failed to create tables and sequences or failed to connect to DB",
            "Failed to create tables and sequences",
            JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadButton = new javax.swing.JButton();
        wordsButton = new javax.swing.JButton();
        phrasesButton = new javax.swing.JButton();
        groupsButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        exportXMLButton = new javax.swing.JButton();
        importXMLButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        uploadButton.setText("Upload new song");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        wordsButton.setText("Words in uploaded songs");
        wordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsButtonActionPerformed(evt);
            }
        });

        phrasesButton.setText("Search phrase");
        phrasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phrasesButtonActionPerformed(evt);
            }
        });

        groupsButton.setText("Create group");
        groupsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupsButtonMouseClicked(evt);
            }
        });

        statisticsButton.setText("Statistics");
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });

        exportXMLButton.setText("Export to XML");
        exportXMLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportXMLButtonActionPerformed(evt);
            }
        });

        importXMLButton.setText("Import XML");
        importXMLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importXMLButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statisticsButton)
                            .addComponent(groupsButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phrasesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exportXMLButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(importXMLButton)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uploadButton)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(uploadButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importXMLButton)
                    .addComponent(wordsButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportXMLButton)
                    .addComponent(phrasesButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(groupsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statisticsButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        UploadPage upload = new UploadPage(currentDB);
        upload.setVisible(true);
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void wordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsButtonActionPerformed
        ViewWordsPage wordsPage = new ViewWordsPage(currentDB);
        wordsPage.setVisible(true);
    }//GEN-LAST:event_wordsButtonActionPerformed

    private void groupsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsButtonMouseClicked
        GroupsPage page = new GroupsPage(currentDB);
        page.setVisible(true);
    }//GEN-LAST:event_groupsButtonMouseClicked

    private void phrasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phrasesButtonActionPerformed
        PhrasesPage page = new PhrasesPage(currentDB);
        page.setVisible(true);
    }//GEN-LAST:event_phrasesButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //if selected to close program, close connection and close program. 
        //If selected cancel/no - do nothing.
        int selected = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to close this window?", "Close Window?", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (selected == JOptionPane.YES_OPTION){
            try {
                currentDB.closeConnection();
                System.exit(0);
            } catch (SQLException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

           
    }//GEN-LAST:event_formWindowClosing

    private void exportXMLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportXMLButtonActionPerformed

        ReadAndWriteXML xml = new ReadAndWriteXML();
        //Try to export
        try {
            xml.exportEntriesToXML(currentDB);
        } catch (ParserConfigurationException | FileNotFoundException | TransformerException ex) {
            JOptionPane.showMessageDialog(this,
            "Export failed on xml parse or file problem.",
            "Export failed",
            JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
            "Export failed on DB: " + ex.getMessage(),
            "Export failed",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_exportXMLButtonActionPerformed

    private void importXMLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importXMLButtonActionPerformed

        //Get selected file
        FileNameExtensionFilter fileFilter=new FileNameExtensionFilter("xml", "xml");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(fileFilter);
        fileChooser.showOpenDialog(null);
        File xmlFile = fileChooser.getSelectedFile();
        //If file was selected, try to import
        if(Objects.nonNull(xmlFile)){
            ReadAndWriteXML xml = new ReadAndWriteXML();
            try {
                xml.importEntriesFromXML(currentDB, xmlFile);
            } catch (ParserConfigurationException | SAXException ex) {
                JOptionPane.showMessageDialog(this,
                "Import failed on parsing xml" ,
                "Import failed",
                JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                "Import failed - failed to open file" ,
                "Import failed",
                JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                "Failed to import to DB" ,
                "Import failed",
                JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_importXMLButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        
        StatisticsPage page = new StatisticsPage(currentDB);
        page.setVisible(true);
    }//GEN-LAST:event_statisticsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
        
    }

    public SQLqueries currentDB;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportXMLButton;
    private javax.swing.JButton groupsButton;
    private javax.swing.JButton importXMLButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton phrasesButton;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JButton uploadButton;
    private javax.swing.JButton wordsButton;
    // End of variables declaration//GEN-END:variables
}
