/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgresqlproject;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Marina Bykov
 */
public class StatisticsPage extends javax.swing.JFrame {
    private int avgNumLettersInLines;
    private int avgNumLettersInSong;
    private int avgNumLettersInVerse;
    private int avgNumLettersInWords;
    private int avgNumWordsInSongs;
    private int avgNumWordsInVerse;
    private int numberOfSongs;
    private int numberOfWordsInSongs;

    
    /**
     * Creates new form StatisticsPage
     */
    public StatisticsPage(SQLqueries currentDB) {
        
        try {
            avgNumLettersInLines = currentDB.getAverageNumberOfCharsInLines();
            avgNumLettersInSong = currentDB.getAverageNumberOfCharsInSongs();
            avgNumLettersInVerse = currentDB.getAverageNumberOfCharsInVerses();
            avgNumLettersInWords = currentDB.getAverageNumberOfCharsInWords();
            avgNumWordsInSongs = currentDB.getAverageNumberOfWordsInSongs();
            avgNumWordsInVerse = currentDB.getAverageNumberOfWordsInVerses();
            numberOfSongs = currentDB.getNumberOfSongs();
            numberOfWordsInSongs = currentDB.getNumberOfWordsInSongs();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
            ex.getMessage(),
            "Failed to get statistics from db",
            JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberOfWordsInSongsLabel = new javax.swing.JLabel();
        numberOfSongsLabel = new javax.swing.JLabel();
        avgNumWordsInSongsLabel = new javax.swing.JLabel();
        avgNumWordsInVerseLabel = new javax.swing.JLabel();
        avgNumLettersInWordsLabel = new javax.swing.JLabel();
        avgNumLettersInVerseLabel = new javax.swing.JLabel();
        avgNumLettersInLineLabel = new javax.swing.JLabel();
        avgNumLettersInSongLabel = new javax.swing.JLabel();
        pageStatisticsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        numberOfWordsInSongsLabel.setText("Number of words in songs: " + numberOfWordsInSongs);

        numberOfSongsLabel.setText("Number of songs: " + numberOfSongs);

        avgNumWordsInSongsLabel.setText("Average number of words in songs: " + avgNumWordsInSongs);

        avgNumWordsInVerseLabel.setText("Average number of words in verses: " + avgNumWordsInVerse);

        avgNumLettersInWordsLabel.setText("Average number of letters in words: " + avgNumLettersInWords);

        avgNumLettersInVerseLabel.setText("Average number of letters in verses: " + avgNumLettersInVerse);

        avgNumLettersInLineLabel.setText("Average number of letters in line: " + avgNumLettersInLines);

        avgNumLettersInSongLabel.setText("Average number of letters in songs: " + avgNumLettersInSong);

        pageStatisticsLabel.setText("Statistics in all songs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avgNumLettersInSongLabel)
                            .addComponent(avgNumLettersInLineLabel)
                            .addComponent(avgNumLettersInVerseLabel)
                            .addComponent(avgNumLettersInWordsLabel)
                            .addComponent(avgNumWordsInVerseLabel)
                            .addComponent(avgNumWordsInSongsLabel)
                            .addComponent(numberOfSongsLabel)
                            .addComponent(numberOfWordsInSongsLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(pageStatisticsLabel)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pageStatisticsLabel)
                .addGap(18, 18, 18)
                .addComponent(numberOfSongsLabel)
                .addGap(18, 18, 18)
                .addComponent(numberOfWordsInSongsLabel)
                .addGap(18, 18, 18)
                .addComponent(avgNumWordsInSongsLabel)
                .addGap(18, 18, 18)
                .addComponent(avgNumWordsInVerseLabel)
                .addGap(18, 18, 18)
                .addComponent(avgNumLettersInWordsLabel)
                .addGap(18, 18, 18)
                .addComponent(avgNumLettersInVerseLabel)
                .addGap(18, 18, 18)
                .addComponent(avgNumLettersInLineLabel)
                .addGap(18, 18, 18)
                .addComponent(avgNumLettersInSongLabel)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgNumLettersInLineLabel;
    private javax.swing.JLabel avgNumLettersInSongLabel;
    private javax.swing.JLabel avgNumLettersInVerseLabel;
    private javax.swing.JLabel avgNumLettersInWordsLabel;
    private javax.swing.JLabel avgNumWordsInSongsLabel;
    private javax.swing.JLabel avgNumWordsInVerseLabel;
    private javax.swing.JLabel numberOfSongsLabel;
    private javax.swing.JLabel numberOfWordsInSongsLabel;
    private javax.swing.JLabel pageStatisticsLabel;
    // End of variables declaration//GEN-END:variables
}
