/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgresqlproject;


import java.sql.SQLException;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Objects;

/**
 *
 * @author Marina Bykov
 */
public class ViewWordsPage extends javax.swing.JFrame {
    private SQLqueries connectedDB;
    private Group[] groups;
    private Song[] songs;
    private List<Song> listOfSongs;
    private List<Group> groupsAsList;
    private Map<String, List<WordAppearance>> wordsFiltered;
    private Integer lineInVerse = null;
    private Integer lineNumberInSong = null;
    private Integer verse = null;
    private Integer wordNumberInLine = null;
    private Integer wordNumberInSong = null;
    private Integer wordNumberInVerse = null;
    private String word = null;
    private Integer groupId = null;
    

    /**
     * Creates new form ViewWordsPage
     */
    public ViewWordsPage(SQLqueries currentDB) {
        this.connectedDB = currentDB;
        try {
            groupsAsList = connectedDB.getGroups();
            groups = new Group[groupsAsList.size()];
            groupsAsList.toArray(groups);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
            ex.getMessage(),
            "Failed to get groups from db",
            JOptionPane.ERROR_MESSAGE);
            groups = new Group[0];
        }
        
        try {
            listOfSongs = connectedDB.getAllSongs();
            songs = new Song[listOfSongs.size()];
            listOfSongs.toArray(songs);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
            ex.getMessage(),
            "Failed to get songs list from db",
            JOptionPane.ERROR_MESSAGE);
            songs = new Song[0];
        }
        
        initComponents();
        selectGroupBox.setSelectedIndex(-1);
        selectSongBox.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        wordsTable = new javax.swing.JTable();
        wordToSearchLabel = new javax.swing.JLabel();
        wordTextField = new javax.swing.JTextField();
        groupLabel = new javax.swing.JLabel();
        selectGroupBox = new javax.swing.JComboBox<>();
        songLabel = new javax.swing.JLabel();
        selectSongBox = new javax.swing.JComboBox<>();
        verseLabel = new javax.swing.JLabel();
        verseTextField = new javax.swing.JTextField();
        wordNumberInSongLabel = new javax.swing.JLabel();
        wordNumberInSongTextField = new javax.swing.JTextField();
        wordNumberInVerseLabel = new javax.swing.JLabel();
        wordNumberInVerseTextField = new javax.swing.JTextField();
        lineInVerseLabel = new javax.swing.JLabel();
        lineInVerseTextField = new javax.swing.JTextField();
        lineNumberInSongLabel = new javax.swing.JLabel();
        lineNumberInSongTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        wordNumberInLineLabel = new javax.swing.JLabel();
        wordNumberInLineTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Words"
            }
        ));
        wordsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(wordsTable);

        wordToSearchLabel.setText("Word to search: ");

        groupLabel.setText("Group of words:");

        selectGroupBox.setModel(new javax.swing.DefaultComboBoxModel<>(groups));

        songLabel.setText("Song:");

        selectSongBox.setModel(new javax.swing.DefaultComboBoxModel<>(songs));

        verseLabel.setText("Verse:");

        verseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verseTextFieldKeyTyped(evt);
            }
        });

        wordNumberInSongLabel.setText("Word number in song:");

        wordNumberInSongTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wordNumberInSongTextFieldKeyTyped(evt);
            }
        });

        wordNumberInVerseLabel.setText("Word number in verse:");

        wordNumberInVerseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wordNumberInVerseTextFieldKeyTyped(evt);
            }
        });

        lineInVerseLabel.setText("Line number in verse:");

        lineInVerseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lineInVerseTextFieldKeyTyped(evt);
            }
        });

        lineNumberInSongLabel.setText("Line number in song:");

        lineNumberInSongTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lineNumberInSongTextFieldKeyTyped(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Filter");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        wordNumberInLineLabel.setText("Word number in line:");

        wordNumberInLineTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wordNumberInLineTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordToSearchLabel)
                    .addComponent(groupLabel)
                    .addComponent(songLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectGroupBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSongBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(verseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordNumberInSongLabel)
                        .addGap(18, 18, 18)
                        .addComponent(wordNumberInSongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordNumberInVerseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(wordNumberInVerseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineInVerseLabel)
                            .addComponent(lineNumberInSongLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lineInVerseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(lineNumberInSongTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(clearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordNumberInLineLabel)
                        .addGap(31, 31, 31)
                        .addComponent(wordNumberInLineTextField)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordToSearchLabel)
                    .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verseLabel)
                    .addComponent(verseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineInVerseLabel)
                    .addComponent(lineInVerseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectGroupBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wordNumberInSongLabel)
                            .addComponent(wordNumberInSongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lineNumberInSongLabel)
                            .addComponent(lineNumberInSongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songLabel)
                    .addComponent(selectSongBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordNumberInVerseLabel)
                    .addComponent(wordNumberInVerseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordNumberInLineLabel)
                    .addComponent(wordNumberInLineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(clearButton))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //Clear current table
        DefaultTableModel model = (DefaultTableModel)wordsTable.getModel();
        model.setRowCount(0);
        //Get search fields and call SELECT method from sql. If search field is empty string or null, pass null to method that will call SELECT.
        word = (wordTextField.getText().isBlank() || wordTextField.getText().isEmpty()) ? null : wordTextField.getText();
        if(!Objects.isNull(word) && !Objects.isNull(selectGroupBox.getSelectedItem())){
            JOptionPane.showMessageDialog(this,
            "Can't search both word and words in group. "
                    + "Please select only group or word, not both.",
            "Group and word selected",
            JOptionPane.ERROR_MESSAGE);
        }
        else {
            //Select parameters, put null if search field is empty
            lineInVerse = (lineInVerseTextField.getText().isEmpty()) 
                    ? null :  Integer.valueOf(lineInVerseTextField.getText());
            lineNumberInSong = (lineNumberInSongTextField.getText().isEmpty()) 
                    ? null : Integer.valueOf(lineNumberInSongTextField.getText());
            verse = (verseTextField.getText().isEmpty()) 
                    ? null : Integer.valueOf(verseTextField.getText());
            wordNumberInLine = (wordNumberInLineTextField.getText().isEmpty()) 
                    ? null : Integer.valueOf(wordNumberInLineTextField.getText());
            wordNumberInSong = (wordNumberInSongTextField.getText().isEmpty()) 
                    ? null : Integer.valueOf(wordNumberInSongTextField.getText());
            wordNumberInVerse = (wordNumberInVerseTextField.getText().isEmpty()) 
                    ? null : Integer.valueOf(wordNumberInVerseTextField.getText());
        
            try {
                wordsFiltered = connectedDB.getWordAppearancesIncludingGroupField(
                        (Group)selectGroupBox.getSelectedItem(), word,
                        (Song)selectSongBox.getSelectedItem(), verse, lineInVerse,
                        wordNumberInVerse, wordNumberInSong,
                        wordNumberInLine, lineNumberInSong);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Couldn't get word appearances",
                JOptionPane.ERROR_MESSAGE);
            }

            //fill table with returned map from SELECT result.
            for (Map.Entry<String, List<WordAppearance>> entry : wordsFiltered.entrySet()) {
                // System.out.println(entry.getKey() + "/" + entry.getValue());
                 model.addRow(Collections.singletonList(entry.getKey()).toArray()); 
            }
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void verseTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verseTextFieldKeyTyped
        consumeOnlyDigit(evt);
    }//GEN-LAST:event_verseTextFieldKeyTyped

    private void wordNumberInSongTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordNumberInSongTextFieldKeyTyped
        consumeOnlyDigit(evt);
    }//GEN-LAST:event_wordNumberInSongTextFieldKeyTyped

    private void wordNumberInVerseTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordNumberInVerseTextFieldKeyTyped
        consumeOnlyDigit(evt);
    }//GEN-LAST:event_wordNumberInVerseTextFieldKeyTyped

    private void lineInVerseTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineInVerseTextFieldKeyTyped
        consumeOnlyDigit(evt);
    }//GEN-LAST:event_lineInVerseTextFieldKeyTyped

    private void lineNumberInSongTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineNumberInSongTextFieldKeyTyped
        consumeOnlyDigit(evt);
    }//GEN-LAST:event_lineNumberInSongTextFieldKeyTyped

    private void wordNumberInLineTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordNumberInLineTextFieldKeyTyped
        consumeOnlyDigit(evt);
    }//GEN-LAST:event_wordNumberInLineTextFieldKeyTyped

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //empty table and empty all search fields
        DefaultTableModel model = (DefaultTableModel)wordsTable.getModel();
        model.setRowCount(0);
        lineInVerseTextField.setText(null);
        lineNumberInSongTextField.setText(null);
        verseTextField.setText(null);
        wordNumberInLineTextField.setText(null);
        wordNumberInSongTextField.setText(null);
        wordNumberInVerseTextField.setText(null);
        wordTextField.setText(null);
        selectGroupBox.setSelectedIndex(-1);
        selectSongBox.setSelectedIndex(-1);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void wordsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordsTableMouseClicked
        int column = 0;
        int row = wordsTable.getSelectedRow();
        String value = wordsTable.getModel().getValueAt(row, column).toString();
        WordAppearancesPage page = new WordAppearancesPage(value, wordsFiltered.get(value));
        page.setVisible(true);
    }//GEN-LAST:event_wordsTableMouseClicked

    
    private void consumeOnlyDigit(java.awt.event.KeyEvent evt)
    {
        char enteredCharacter = evt.getKeyChar();
        if(!Character.isDigit(enteredCharacter))
            evt.consume();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lineInVerseLabel;
    private javax.swing.JTextField lineInVerseTextField;
    private javax.swing.JLabel lineNumberInSongLabel;
    private javax.swing.JTextField lineNumberInSongTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<Group> selectGroupBox;
    private javax.swing.JComboBox<Song> selectSongBox;
    private javax.swing.JLabel songLabel;
    private javax.swing.JLabel verseLabel;
    private javax.swing.JTextField verseTextField;
    private javax.swing.JLabel wordNumberInLineLabel;
    private javax.swing.JTextField wordNumberInLineTextField;
    private javax.swing.JLabel wordNumberInSongLabel;
    private javax.swing.JTextField wordNumberInSongTextField;
    private javax.swing.JLabel wordNumberInVerseLabel;
    private javax.swing.JTextField wordNumberInVerseTextField;
    private javax.swing.JTextField wordTextField;
    private javax.swing.JLabel wordToSearchLabel;
    private javax.swing.JTable wordsTable;
    // End of variables declaration//GEN-END:variables
}
